[package]
name = "os-rust-shell"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
atty = "0.2"
nix = "0.23.0"
lazy_static = "1.4.0"
